### PR TITLE
Update classes.md

### PR DESCRIPTION
**Pull request by wuanunet**
Modify Markdown Bold font.

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/classes.md](https://github.com/wuanunet/docs.zh-tw/blob/patch-1/docs/csharp/classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-tw/dotnet-new/articles/csharp/classes?branch=pr-zh-tw-100) | [Details](#user-content-docs%2Fcsharp%2Fclasses.md)

<a name="docs%2Fcsharp%2Fclasses.md"></a>
### [docs/csharp/classes.md](https://github.com/wuanunet/docs.zh-tw/blob/patch-1/docs/csharp/classes.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/docs/standard/garbagecollection/gc.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705161446325739-100%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kkbruce** [comment]
你是移除 Bold 嗎？不太對哦。
兩個 \*\* 是要 \*「...」\* ，而不是移除哦。

**Comment by wuanunet** [comment]
@kkbruce 
不好意思，我誤解了，那我先關閉這個 PR。
感謝 Bruce 提醒。

**Comment by kkbruce** [comment]
@wuanunet  一起加油。 :-)

**Comment by Clarare** [comment]
@wuanunet  Thank you for your feedback and suggestion! 
		
We found some technical reasons> which is not fully aligned to our acceptance criterial, I am closing this PR. 
		
Microsoft C&E Localization Team

**Pull request closed without merging**
