### PR TITLE
Fix translations and marks

### PR DESCRIPTION
**Pull request by NextTurn**
Similar to dotnet/docs.ko-kr#87, dotnet/docs.pt-br#103, dotnet/docs.zh-cn#297

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @NextTurn , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by NextTurn** [comment]
Please stop adding more errors.

**Comment by v-radelg** [comment]
@NextTurn , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Comment by srvbpigh** [comment]
@NextTurn：

再次感謝您提供建議！ 我們同意您的建議，而且我們將會合併此 PR。您的建議也會用於下一次文章更新。

 
感謝您，

Microsoft DOCS 全球體驗小組

**Pull request merged**
