### PR TITLE
Update dependencies.md

### PR DESCRIPTION
**Pull request by Noirwada**
remove space

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/tools/dependencies.md](https://github.com/Noirwada/docs.zh-tw/blob/patch-1/docs/core/tools/dependencies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/dotnet-new/articles/core/tools/dependencies?branch=pr-zh-tw-103) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705170608073727-103%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kkbruce** [comment]
Hi @Noirwada 

"## The new \<PackageReference> element" markdown can't display \<PackageReference> in title, add \ to escape.

I have report same problem to en-us docs, too.

**Comment by gosali** [comment]
Hi @Noirwada , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@Noirwada , Thank you for your feedback and suggestion! 
		
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
		
Microsoft C&E Localization Team

**Pull request merged**
