### PR TITLE
Live

### PR DESCRIPTION
**Pull request by gosali**

### CODE REVIEW

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\pa3y-s, target branch: master, target branch commit: 8da828e7082beb42ec745e3202e748d8962f5d46, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C8%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705081537153992-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\nvyb-s, target branch: master, target branch commit: 093f9065fa72e2ceea6a30dc301c7d9aec172683, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705161904508258-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\harb-s, target branch: master, target branch commit: 093f9065fa72e2ceea6a30dc301c7d9aec172683, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705161905456569-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\2slt-s, target branch: master, target branch commit: 093f9065fa72e2ceea6a30dc301c7d9aec172683, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705162011157276-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\oyey-s, target branch: master, target branch commit: 093f9065fa72e2ceea6a30dc301c7d9aec172683, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705162013586155-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\1c50-s, target branch: master, target branch commit: 093f9065fa72e2ceea6a30dc301c7d9aec172683, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705162018097831-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\glon-s, target branch: master, target branch commit: 8e625f683b2f064f402b7678e96bf9bad4da8430, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705171631160265-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\smlk-s, target branch: master, target branch commit: 8e625f683b2f064f402b7678e96bf9bad4da8430, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705171829505811-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\c15d-s, target branch: master, target branch commit: 8e625f683b2f064f402b7678e96bf9bad4da8430, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705171830309074-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\kz4h-s, target branch: master, target branch commit: 8e625f683b2f064f402b7678e96bf9bad4da8430, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705171901408533-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-tw, working directory: W:\mlg4-s, target branch: master, target branch commit: 8aadb1274de1b3fd9bdc09b9f170f17d8aa1d226, source branch: live, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705171916478409-62%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nokura** [comment]
We are not ready to merge to Live

**Pull request closed without merging**
