### PR TITLE
Update library-with-visual-studio-2017.md

### PR DESCRIPTION
**Pull request by alantsai**
fix markdown bold syntax error

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/getting-started/library-with-visual-studio-2017.md](https://github.com/alantsai/docs.zh-tw/blob/patch-2/docs/csharp/getting-started/library-with-visual-studio-2017.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-tw/dotnet-new/articles/csharp/getting-started/library-with-visual-studio-2017?branch=pr-zh-tw-65) | [Details](#user-content-docs%2Fcsharp%2Fgetting-started%2Flibrary-with-visual-studio-2017.md)

<a name="docs%2Fcsharp%2Fgetting-started%2Flibrary-with-visual-studio-2017.md"></a>
### [docs/csharp/getting-started/library-with-visual-studio-2017.md](https://github.com/alantsai/docs.zh-tw/blob/patch-2/docs/csharp/getting-started/library-with-visual-studio-2017.md)
 - **Line 25**: **[Warning]** Invalid file link:(~/docs/standard/library.md).
 - **Line 37**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/solution.jpg).
 - **Line 41**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/vs_with_solution.jpg).
 - **Line 53**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/lib_project.jpg).
 - **Line 57**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/class_library.jpg).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C9%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705091338539804-65%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CeciAc** [comment]
Hi **@alantsai**  we are still in discussing, will update the decision later soon. 
_Thanks for your support,
Microsoft C&E Localization Team_

**Comment by kkbruce** [comment]
Same #59 .

**Comment by kkbruce** [comment]
Same #58 .

**Comment by alantsai** [comment]
Sorry didn't realize there was a pull request on the same file
closing this one

**Pull request closed without merging**
