### PR TITLE
csharp-7-1.md init初始化及翻譯條目 - init csharp-7-1.md and translate

### PR DESCRIPTION
**Pull request by kirigakuretora**
第一次逐步小段落翻譯對應條目What's new in C# 7.1,  編譯可能有點不通順,  再麻煩前輩指教

### CODE REVIEW

**Comment by mairaw** [comment]
@gosali @nokura who's taking care of this one? Should @kirigakuretora fix the merge conflicts?

**Comment by kirigakuretora** [comment]
Dear @mairaw:

my name is kirigakuretora(霧隠虎),kirigakuretora is sorry , Because is busy work, cannot concentrate on writing.

**Comment by mairaw** [comment]
Don't worry 霧隠虎 (@kirigakuretora). I'm following up with the team on why this hasn't been reviewed. Thanks for your contribution!

**Comment by gosali** [comment]
Hi @kirigakuretora , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@kirigakuretora : Thank you for your feedback and suggestion! 
  
The feedback is considered. We will tune part of  your feedbacks in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
  
Microsoft C&E Localization Team

**Pull request merged**
