### PR TITLE
Update implicitly-typed-local-variables.md

### PR DESCRIPTION
**Pull request by cashwu**
modify the translation

### CODE REVIEW

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml](https://github.com/cashwu/docs.zh-tw/blob/master/api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml) | :x:Error | | [Details](#user-content-api%2FSystem.Threading.Tasks.Dataflow.ActionBlock-1.yml)
[docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md) | :warning:Warning | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fimplicitly-typed-local-variables.md)

<a name="api%2FSystem.Threading.Tasks.Dataflow.ActionBlock-1.yml"></a>
### [api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml](https://github.com/cashwu/docs.zh-tw/blob/master/api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml)
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fimplicitly-typed-local-variables.md"></a>
### [docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md)
 - **Line 106**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C30%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201707300900504935-129%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml](https://github.com/cashwu/docs.zh-tw/blob/master/api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml) | :x:Error | | [Details](#user-content-api%2FSystem.Threading.Tasks.Dataflow.ActionBlock-1.yml)
[docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md) | :warning:Warning | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Farrays%2Fimplicitly-typed-arrays.md)
[docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md) | :warning:Warning | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fimplicitly-typed-local-variables.md)

<a name="api%2FSystem.Threading.Tasks.Dataflow.ActionBlock-1.yml"></a>
### [api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml](https://github.com/cashwu/docs.zh-tw/blob/master/api/System.Threading.Tasks.Dataflow.ActionBlock-1.yml)
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 3**: **[Error]** Unable to resolve  [!code-csharp[TPLDataflow_DegreeOfParallelism#2](~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs#2)]
. Can not find reference ~/snippets/csharp/VS_Snippets_Misc/tpldataflow_degreeofparallelism/cs/dataflowdegreeofparallelism.cs.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 4**: **[Error]** Unable to resolve  [!code-vb[TPLDataflow_DegreeOfParallelism#2](~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb#2)]. Can not find reference ~/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_degreeofparallelism/vb/dataflowdegreeofparallelism.vb.
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md).

<a name="docs%2Fcsharp%2Fprogramming-guide%2Farrays%2Fimplicitly-typed-arrays.md"></a>
### [docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md)
 - **Line 43**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fimplicitly-typed-local-variables.md"></a>
### [docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md)
 - **Line 106**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C30%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201707300939035805-129%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @cashwu , we are still in discussing, will update the decision later soon. 

*Please bear in mind that modifying multiple files in the same PR is not a valid procedure. Just for this time the feedback will be considered, in future opportunities the PR will be closed*
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by cashwu** [comment]
Hi @v-radelg , 

I am sorry about it, I will pay attention next time 
Thank your help

**Comment by v-radelg** [comment]
@cashwu : Thank you for your feedback and suggestion! 

The feedback is considered. We will tune part of  your feedback in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
		
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@mairaw, Could you please change the base branch from Master to Live?

**Comment by mairaw** [comment]
@gosali done.

**Comment by mairaw** [comment]
@gosali @cashwu this now has conflict issues that must be resolved and I'm afraid to do this because I don't speak the language

**Comment by cashwu** [comment]
@mairaw , @gosali , I try to resolved the confilict , please help to check the merge

**Comment by olprod** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/getting-started/testing-library-with-visual-studio.md) | :x:Error | [View](https://review.docs.microsoft.com/zh-tw/dotnet/csharp/getting-started/testing-library-with-visual-studio?branch=pr-zh-tw-129) | [Details](#user-content-docs%2Fcsharp%2Fgetting-started%2Ftesting-library-with-visual-studio.md)
[docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-tw/dotnet/csharp/programming-guide/arrays/implicitly-typed-arrays?branch=pr-zh-tw-129) | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Farrays%2Fimplicitly-typed-arrays.md)
[docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-tw/dotnet/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables?branch=pr-zh-tw-129) | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fimplicitly-typed-local-variables.md)
[docs/csharp/language-reference/keywords/var.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/language-reference/keywords/var.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/dotnet/csharp/language-reference/keywords/var?branch=pr-zh-tw-129) |

<a name="docs%2Fcsharp%2Fgetting-started%2Ftesting-library-with-visual-studio.md"></a>
### [docs/csharp/getting-started/testing-library-with-visual-studio.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/getting-started/testing-library-with-visual-studio.md)
 - **Line 82**: **[Error]** Tag name 1 is not found when resolving &quot;[!CODE-csharp[Test#1](../../../samples/snippets/csharp/getting_started/with_visual_studio_2017/testlib1.cs#1)]&quot;
 - **Line 22**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/library-with-visual-studio-2017.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/testproject.jpg).
 - **Line 38**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/unit_test_code_window.jpg).
 - **Line 52**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/add_reference.jpg).
 - **Line 96**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/first_test.jpg).
 - **Line 111**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/failed_test.jpg).
 - **Line 115**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/failed_test2.jpg).
 - **Line 127**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/media/lib_release.jpg).
 - **Line 133**: **[Warning]** Invalid file link:(~/docs/csharp/getting-started/consuming-library-with-visual-studio-2017.md).

<a name="docs%2Fcsharp%2Fprogramming-guide%2Farrays%2Fimplicitly-typed-arrays.md"></a>
### [docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md)
 - **Line 43**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fimplicitly-typed-local-variables.md"></a>
### [docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/cashwu/docs.zh-tw/blob/master/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md)
 - **Line 105**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C2%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201709021433272050-129%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
