### PR TITLE
Update using-on-windows-full-solution.md

### PR DESCRIPTION
**Pull request by poychang**
1. changed keyword to bold
2. rename the project name "應用程式" to "App"

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/tutorials/using-on-windows-full-solution.md](https://github.com/poychang/docs.zh-tw/blob/patch-4/docs/core/tutorials/using-on-windows-full-solution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/dotnet-new/articles/core/tutorials/using-on-windows-full-solution?branch=pr-zh-tw-89) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201705160214084806-89%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Clarare** [comment]
Hi @poychang , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by Clarare** [comment]
@poychang  Thank you for your feedback and suggestion! 
		
We found are the changes are not consistent with the ZHTW style guide, which is not fully aligned to our acceptance criterial, I am closing this PR. 
		
Microsoft C&E Localization Team

**Comment by kkbruce** [comment]
Hi @Clarare 
Visual Studio create new project name use 「App」is  correct, 
Project name "App" don't translation to「應用程式」, use Chinese word in project name is incorrect.

**Comment by poychang** [comment]
@kkbruce thanks for explain!

**Pull request closed without merging**
