### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by kkbruce**
.NET Core 不需翻譯為「.NET 核心」。
修正一些單字大小寫問題。

### CODE REVIEW

**Comment by LeoCYang** [comment]
I agree with @kkbruce suggestion that .NET Core should not be translated to ".NET 核心".  Leave it as .NET Core in the document.

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/index.md](https://github.com/kkbruce/docs.zh-tw/blob/patch-1/docs/core/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-tw/dotnet/articles/core/index?branch=pr-zh-tw-11) | [Details](#user-content-docs/core/index.md)

<a name="docs/core/index.md"></a>
### [docs/core/index.md](https://github.com/kkbruce/docs.zh-tw/blob/patch-1/docs/core/index.md)
 - **Line 115**: **[Warning]** Invalid file link:(~/docs/images/corefx-platforms-loc.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C28%5Cae81b966-19ba-0dc6-ce1c-ced5e89ee923%5CPullRequest%5C201703281540485855-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @kkbruce , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@kkbruce , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
		
Microsoft C&E Localization Team

**Pull request merged**
